import type {UsbDiagnosticsSnapshot} from '../src/utils/era-usb-diagnostics';

export const diagnosticSnapshot = (
  extras: Partial<UsbDiagnosticsSnapshot> = {},
): UsbDiagnosticsSnapshot => ({
  protocolVersion: 1,
  state: 2,
  sessionId: 3,
  sequence: 9,
  pollingMode: 3,
  speed: 2,
  durationSeconds: 30,
  elapsedMs: 30000,
  expectedIntervalUs: 125,
  reportSamples: 100,
  latencyMinUs: 40,
  latencyAverageUs: 90,
  latencyMaxUs: 625,
  intervalLatencyMaxUs: 300,
  queueDepthPeak: 2,
  histogram: [25, 25, 45, 3, 1, 0, 1, 0],
  loopSamples: 1000,
  loopGapMaxUs: 2400,
  intervalLoopGapMaxUs: 1200,
  loopStallCount: 1,
  loopStallThresholdUs: 1000,
  bootCounters: {
    reportDrops: 4,
    usbResets: 3,
    configurations: 2,
    suspends: 1,
    speedChanges: 0,
  },
  sessionCounters: {
    reportDrops: 0,
    usbResets: 0,
    configurations: 0,
    suspends: 0,
    speedChanges: 0,
  },
  timelineOverwrites: 0,
  events: [{type: 6, relativeMs: 15000, value: 2400}],
  ...extras,
});
