name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, fiber]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install --frozen-lockfile
      - name: Test (p1)
        run: bun run test:p1
      - name: Build
        run: |
          bun run build
